version: "3.7"
services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    depends_on:
      - mariadb
    ports:
      - 8080:8080
  backend:
    build: ./backend
    depends_on:
      - mariadb
    ports:
      - 10000:10000
  frontend:
    build: ./frontend
    ports:
      - 10001:80