version: "3"
services:
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080