server:
  port: 10000
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: graphql_notes
    password: graphql_notes
    url: jdbc:mariadb:failover://mariadb:3306/graphql_notes?autoReconnect=true
    platform: org.hibernate.dialect.MariaDB103Dialect
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
  flyway:
    clean-on-validation-error: true
    baseline-on-migrate: true
    baseline-version: 0.0
  main:
    allow-bean-definition-overriding: true #FIXME keycloak issue

graphql:
  spqr:
    gui:
      enabled: true
    ws:
      endpoint: "/graphql-ws"
      enabled: true

keycloak:
  realm: master
  auth-server-url: http://keycloak:8080/auth
  resource: graphql-notes
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true

logging:
  level:
    org.keycloak: TRACE