server:
  port: 10000
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    username:
    url: jdbc:h2:mem:testdb
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  flyway:
    clean-on-validation-error: true
    baseline-on-migrate: true
    baseline-version: 0.0
  main:
    allow-bean-definition-overriding: true #FIXME keycloak issue

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth
  resource: graphql-notes
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true

logging:
  level:
    org.keycloak: TRACE


graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"